import { test, expect } from '@playwright/test';
import process from 'node:process';
import { Buffer } from 'node:buffer';

test('bulk sources, external creative link, frozen metadata, patterns and pause', async ({ page, request }) => {
    test.skip(process.env.ANALYTICS_DEMO !== '1', 'Requires isolated PostgreSQL/API with simulated providers');
    test.setTimeout(90000);
    const api = process.env.TEST_API_URL;
    expect(new URL(api).hostname).toBe('127.0.0.1');
    const login = await request.post(`${api}/auth/login/json`, { data: { email: process.env.TEST_EMAIL, password: process.env.TEST_PASSWORD } });
    expect(login.ok()).toBeTruthy();
    const token = (await login.json()).access_token;
    const headers = { Authorization: `Bearer ${token}` };
    await page.addInitScript(value => localStorage.setItem('accessToken', value), token);
    await page.goto('/creative-analytics');
    await page.getByRole('button', { name: 'Data sources', exact: true }).click();
    for (const name of ['Google · test-google', 'TikTok · test-tiktok']) {
        await page.getByRole('combobox', { name: 'Connected source', exact: true }).click();
        await page.getByRole('option', { name, exact: true }).click();
        await page.getByRole('button', { name: 'Enable selected source' }).click();
        await expect(page.getByRole('button', { name: 'Enable selected source' })).toBeEnabled();
    }
    expect((await request.post(`${api.replace('/api/v1', '')}/test-analytics/tick`)).ok()).toBeTruthy();
    await page.reload();
    await page.getByRole('button', { name: 'Data sources', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Google · test-google-account' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'TikTok · test-tiktok-account' })).toBeVisible();
    await page.getByRole('button', { name: 'Patterns', exact: true }).click();
    await expect(page.getByText('Stronger evidence').first()).toBeVisible();
    await page.getByLabel('Platform', { exact: true }).selectOption('google');
    await page.getByRole('button', { name: 'Imported ads', exact: true }).click();
    await page.getByLabel('Only ads needing a creative link').check();
    await page.getByRole('button', { name: 'Link creative', exact: true }).click();
    const name = `test-analytics-upload-${Date.now()}.png`;
    await page.getByLabel('Upload external creative', { exact: true }).setInputFiles({ name, mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jA1sAAAAASUVORK5CYII=', 'base64') });
    await expect(page.getByRole('button', { name: 'Save creative link', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Save creative link', exact: true }).click();
    await expect(page.getByText('Creative linked with your user and metadata revision')).toBeVisible();
    const imported = (await (await request.get(`${api}/analytics/ads?platform=google&limit=100`, { headers })).json()).data;
    const linked = imported.find(row => row.name === 'test-remote-0-0');
    expect(linked.creative_snapshot.source_type).toBe('external_upload');
    expect(linked.linked_by_id).toBe(linked.creative_snapshot.created_by_id);
    const asset = (await (await request.get(`${api}/creatives/${linked.creative_asset_id}`, { headers })).json());
    const updated = await request.patch(`${api}/creatives/${asset.id}`, { headers, data: { expected_revision: asset.metadata_revision, metadata: { ...asset.metadata, lighting: 'changed-after-link' } } });
    expect(updated.ok()).toBeTruthy();
    const report = await request.get(`${api}/analytics/report?platform=google`, { headers });
    expect(report.ok()).toBeTruthy();
    expect((await report.json()).data.find(row => row.external_ad_id === linked.external_id).snapshot.metadata.lighting).toBe('natural');
    await page.getByRole('button', { name: 'Daily performance', exact: true }).click();
    await expect(page.getByRole('cell', { name: '100.290000', exact: true }).first()).toBeVisible();
    await page.getByRole('button', { name: 'Data sources', exact: true }).click();
    await page.getByRole('button', { name: 'Pause source', exact: true }).first().click();
    await expect(page.getByRole('button', { name: 'Resume source', exact: true })).toBeVisible();
    const viewer = await request.post(`${api}/auth/login/json`, { data: { email: 'test-analytics-viewer@example.com', password: process.env.TEST_PASSWORD } });
    expect(viewer.ok()).toBeTruthy();
    const viewerHeaders = { Authorization: `Bearer ${(await viewer.json()).access_token}` };
    expect((await (await request.get(`${api}/analytics/report`, { headers: viewerHeaders })).json()).data).toEqual([]);
    expect((await request.put(`${api}/analytics/settings/google`, { headers: viewerHeaders, data: {} })).status()).toBe(403);
});
